"""Añadimos campos al modelo Miembro

Revision ID: e23856f38fd2
Revises: 4a47f1d24e36
Create Date: 2024-10-29 16:53:19.311758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e23856f38fd2'
down_revision = '4a47f1d24e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Foto', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('MotivoReduccion', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('instrumento_principal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instrumento_banda_escuela_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instrumento_banda_titular_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('miembros_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('miembros_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('miembros_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'instrumentos', ['instrumento_banda_escuela_id'], ['id'])
        batch_op.create_foreign_key(None, 'instrumentos', ['instrumento_banda_titular_id'], ['id'])
        batch_op.create_foreign_key(None, 'instrumentos', ['instrumento_principal_id'], ['id'])
        batch_op.drop_column('InstrumentoBandaEscualaId')
        batch_op.drop_column('MotivoReduccioCuota')
        batch_op.drop_column('InstrumentoBandaTitularId')
        batch_op.drop_column('InstrumentoId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('InstrumentoId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('InstrumentoBandaTitularId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('MotivoReduccioCuota', mysql.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('InstrumentoBandaEscualaId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('miembros_ibfk_1', 'instrumentos', ['InstrumentoBandaEscualaId'], ['id'])
        batch_op.create_foreign_key('miembros_ibfk_2', 'instrumentos', ['InstrumentoBandaTitularId'], ['id'])
        batch_op.create_foreign_key('miembros_ibfk_3', 'instrumentos', ['InstrumentoId'], ['id'])
        batch_op.drop_column('instrumento_banda_titular_id')
        batch_op.drop_column('instrumento_banda_escuela_id')
        batch_op.drop_column('instrumento_principal_id')
        batch_op.drop_column('MotivoReduccion')
        batch_op.drop_column('Foto')

    # ### end Alembic commands ###
